services:
  - type: web
name: secure-web-demo-react
env: node
plan: free
buildCommand: "cd ../client && npm ci && npm run build && cd ../server && npm ci"
startCommand: "node app.js"
autoDeploy: true
